# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a58a82969b3124d7963efc705756074b0f0f1c189305080cfbf14ac683c39f98acdaa06e62ae728c278ba5f8696442a43cb614df495c1d03acc1c12bede0a30

test:
  secret_key_base: 79ad9d977ad96a12c5d0392c597908dfb7e93fec5667883cca5337c8c730ede69b8eace3f1e015e5da1a15c687874f135e35256fc03d316c1dc7ee53b141ac1a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
